export const ACCOUNT_STATUS = {
  SIGNED_UP: "SIGNED_UP",
  EMAIL_VERIFIED: "EMAIL_VERIFIED",
  PAYMENT_PROCESSING: "PAYMENT_PROCESSING",
  SUBSCRIPTION_ACTIVE: "SUBSCRIPTION_ACTIVE",
  ACCOUNT_READY: "ACCOUNT_READY",
  SUSPENDED: "SUSPENDED",
  CANCELLED: "CANCELLED",
  DELETED: "DELETED",
};
